from . import ipmc_banks
from . import ipmc_cities
from . import ipmc_nationalities
from . import ipmc_qualifications
from . import ipmc_job_sectors
from . import ipmc_job_opportunities
from . import ipmc_employment_status
from . import ipmc_applicants
from . import ipmc_application_announcement
